### ISSUE TITLE
CLI changes

### ISSUE THREAD

**Issue by stemaMSFT** [Azure/aztfy#222]
Note all changes detailed here are to the `-rg --resource-group` mode of aztfy.
- ~Remove `-batch` flag and instead default to batch behavior of running non-interactively~ Delayed
- ~add a `-interactive -i` to access the UI for those who would still want to use it.~ Delayed
- [x] Change `--batch -b` to ~`--quiet -q`~ `--non-interactive`/`-n`. (#242)
- [x] tag for `--hcl-only` to only import the HCL files. (#246)
- [x] add a `-generate -g` tag to just generate a mapping file based on the specified resource group. (#240)
- [x] New subcommand `map`/`mapping-file` to consume the mapping file, and removing the original `-m` option from `rg` and `query` subcommands. (#241)
- [x] Makes all subcommands consistent about interactive/non-interactive modes (#243) 
 
Though not directly CLI related, within interactive mode having an option to export just HCL and keep "w" as export HCL and state is also a feature change.

**Comment by magodo** [comment]
@stemaMSFT I still feel it is not so convincing to switch the `--batch` and `--interactive` mode, that is just a matter of personal taste. I mean changing this might help some pipeline users, but it will hurt the other half. Also, I would encourage users to use it in interactive mode so that they have a better overview of the resource list to be terrafied before proceeding.

Regarding the `--exclude-state`, we can only keep the long name, as the short name `-s` confuses the users for the opposite meaning. Or we can just change it to `--mutate-state` with `-s` as the short name. However, we needs more consideration when introducing this:

1. State must be mutated when `--append` is set
2. State must be mutated when remote backend is specified (as in this case, `--append` is always on)
3. The `--output-dir` and `--overwrite` are not needed if state is to be excluded, because in this case the output dir is a temporary directory, which is to be removed afterwards
4. In interactive mode, we can continue using <kbd>w</kbd> to do either saving the state and hcl in an output directory, or just print the HCL, depending on how that option is specified

Regarding `--generate`, it might be better to be more specific like: `--generate-mapping-file`?

**Comment by stemaMSFT** [comment]
Hey @magodo, I'll try to address these items one at a time.

The thinking for `--batch` being default is that while interactive mode is more useful for new users, a command non-interactive mode would quickly become the default day to day use for customers. While I'm okay with keeping the interactive mode as default, I do think rather than it being a half pipeline users or half non-pipeline users, I see it more as 75% users not needing the interactive mode and actually preferring the non-interactive mode based on our customer research feedback. It can be an easily reverted change in the future if it turns out this was not the correct change to make, but as far as we believe it is. Regardless, if we don't go this route, I think renaming `--batch -b` to `--non-interactive -n` will generate more clarity for customers and I'd strongly recommend that action instead.

For the state issue, mutate state does sound quite complex, so I'd like to avoid that rename. For now, I'd suggest we call the command `--exclude-state` with maybe short form `-es`. If that sounds okay with you, I'll address the points here:

1. My only concern with this is if overwriting occurs if `--append` is not specified on the entire directory. This may be my own confusion about the command, but my assumption up until now was that the entire directory would be rewritten if `--append` was not specified. Since point 3 seems to say that this wouldn't be the case, I'd appreciate if you could confirm that the default behavior would not rewrite an entire directory. 
2. If that's the case I'd agree on point 1 and point 2, the difference being for the `exclude-state` command; throw some sort of error/exception if users try to both `--exclude-state` and `--append` to existing state.
3. I agree with you on point 3, that `--output-dir` and `--overwrite` commands aren't needed. 
4. For point 4, can we instead have interactive mode not take `--exclude-state` and have an option within the UI to import just HCL and not state? I'd imagine a lot of customers will import both state and HCL on accident if the `w` command is the same for both.

Regarding `--generate`, I see no issues with `--generate-mapping-file` as the command name, so long as we have `-g` short form available!

**Comment by magodo** [comment]
@stemaMSFT I still want to further confirm with you abou the `--hcl-only` (prev. `--exclude-state`) option. Could you please confirm the following behavior is expected with this option:

- This option conflicts with `--append` and the remote backend options
- The `--output-dir` and `--overwrite` is still available, since the directory is needed to hold the resource mapping file and the skipped resources file
- The only difference between with or with out this option is whether we delete the *.terraform* directory and the state file from the output directory

**Comment by magodo** [comment]
@stemaMSFT For the batch mode, currently it is not totally quiet at all. E.g. when terrafying a resource gorup, it will print the progress information. Additionally, it has a hidden flag `--plain-ui`, which makes the progress information printed line-by-line, which is currently only for testing purpose. So I'm hesitating to change the option to be `--quiet`/`-q`. WDYT?

**Comment by magodo** [comment]
@stemaMSFT In #240, there is one caveat is that although the `res` mode supports export the mapping file, it doesn't support feeding the mapping file yet. Though we can add that support, however, I think instead of supporting the `-m` for each `res`/`query`/`rg` mode, the intuitive way to do is to introduce anther subcommand `map`/`mapping-file` to accept a path to a mapping file. Then only terrafies the specified resources in that file. We can make this mode non-interactive only (just like the `res` mode).

The reason why previously we would need to support `-m` in the `rg` mode separately, is because we need the ARM template to get the cross resource dependencies. But now we can resolve that ourselves.

**Comment by stemaMSFT** [comment]
@magodo would map command consume a preexisting mapping file or generate a mapping file from scratch? Main confusion I have with this is understanding that point. If it's consuming a preexisting mapping file, I think it's okay to have that as a separate command since it could technically take the mapping file from anywhere. If it's to generate a mapping file from a resource or a query, I'd also think that a separate command would be good for that. Not sure how @grayzu feels. However, at this point it's becoming the `generate` command from our original workflow diagram. I think it could be good to just call it `aztfy generate` as we previously did.

**Comment by stemaMSFT** [comment]
Also, to confirm on the previous two comments, `—hcl-only` behavior looks correct to me. Can we possibly use a short form of `-h` or no? I’m also ok with calling it `—non-interactive -n`. You can go ahead with both changes!

**Comment by magodo** [comment]
@stemaMSFT All the items for this issue has been addressed. Can we close this for now?

**Comment by stemaMSFT** [comment]
Hey @magodo, sorry I just saw this. Closed it!
